package com.university.placementsystem.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Entity representing a student's application to a specific {@link JobPosting}.
 *
 * <p>Stores the applicant (student), target job, application status,
 * and the timestamp when the application was submitted.</p>
 */
@Entity
@Table(name = "applications")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Application {

    // Primary key (auto-generated by the database)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Student who submitted the application (many applications per student)
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "student_id", nullable = false)
    private Student student;

    // Job posting being applied to (many applications per job)
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "job_posting_id", nullable = false)
    private JobPosting jobPosting;

    // Current status of the application (APPLIED, SHORTLISTED, SELECTED, REJECTED)
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ApplicationStatus status;

    // Timestamp when the application was created
    @Column(name = "applied_at", nullable = false, updatable = false)
    private LocalDateTime appliedAt;

    /**
     * Initializes {@code appliedAt} and sets default status before persisting.
     */
    @PrePersist
    protected void prePersist() {
        this.appliedAt = LocalDateTime.now();
        if (status == null) {
            this.status = ApplicationStatus.APPLIED;
        }
    }
}
