package com.university.placementsystem.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Entity representing a job posting created by an {@link Organization}.
 *
 * <p>Each posting includes a title, description, skills, eligibility criteria,
 * and creation timestamp. A posting always belongs to one organization.</p>
 */
@Entity
@Table(name = "job_postings")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class JobPosting {

    // Primary key (auto-generated by the database)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Job title
    @Column(nullable = false, length = 200)
    private String title;

    // Detailed job description
    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;

    // Comma-separated list of required skills
    @Column(name = "skills_required", length = 500)
    private String skillsRequired;

    // Eligibility criteria for applicants
    @Column(name = "eligibility_criteria", length = 500)
    private String eligibilityCriteria;

    // Timestamp of creation (set automatically before persist)
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // Owning organization (many postings can belong to one organization)
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "organization_id", nullable = false)
    private Organization organization;

    /**
     * Sets {@code createdAt} just before persisting.
     * Ensures the timestamp is generated automatically.
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }
}
