package com.university.placementsystem.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;

/**
 * Entity representing an organization profile in the Placement System.
 *
 * <p>Each organization is linked to exactly one {@link User} account and
 * stores details such as company name, industry, location, description,
 * and approval status (managed by the admin).</p>
 */
@Entity
@Table(name = "organizations")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Organization {

    // Primary key (auto-generated by the database)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Associated user account (1-to-1, unique per organization)
    @NotNull(message = "User cannot be null")
    @OneToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    // Company name (required)
    @NotBlank(message = "Company name cannot be blank")
    @Column(nullable = false, length = 150)
    private String companyName;

    // Industry (optional, e.g., IT, Finance, Healthcare)
    @Column(length = 100)
    private String industry;

    // Location (optional, city or region)
    @Column(length = 150)
    private String location;

    // Description of the company (optional, up to 500 chars)
    @Column(length = 500)
    private String description;

    // Whether the organization is approved by the admin
    @Column(nullable = false)
    private boolean approved = false;
}
